# CMake generated Testfile for 
# Source directory: /home/chaste/src/projects/Mammary/test
# Build directory: /home/chaste/projects/Mammary/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(TestHello "/home/chaste/projects/Mammary/test/TestHello")
set_tests_properties(TestHello PROPERTIES  LABELS "Continuous_project_Mammary" PROCESSORS "1" WORKING_DIRECTORY "/home/chaste/src/")
add_test(2DTest "/home/chaste/projects/Mammary/test/2DTest")
set_tests_properties(2DTest PROPERTIES  LABELS "Continuous_project_Mammary" PROCESSORS "1" WORKING_DIRECTORY "/home/chaste/src/")
add_test(TestBscOdeSystem "/home/chaste/projects/Mammary/test/TestBscOdeSystem")
set_tests_properties(TestBscOdeSystem PROPERTIES  LABELS "Continuous_project_Mammary" PROCESSORS "1" WORKING_DIRECTORY "/home/chaste/src/")
add_test(TestBscTrackingModifier "/home/chaste/projects/Mammary/test/TestBscTrackingModifier")
set_tests_properties(TestBscTrackingModifier PROPERTIES  LABELS "Continuous_project_Mammary" PROCESSORS "1" WORKING_DIRECTORY "/home/chaste/src/")
add_test(TestLumenKiller "/home/chaste/projects/Mammary/test/TestLumenKiller")
set_tests_properties(TestLumenKiller PROPERTIES  LABELS "Continuous_project_Mammary" PROCESSORS "1" WORKING_DIRECTORY "/home/chaste/src/")
add_test(TestOrganoidCellCycleModel "/home/chaste/projects/Mammary/test/TestOrganoidCellCycleModel")
set_tests_properties(TestOrganoidCellCycleModel PROPERTIES  LABELS "Continuous_project_Mammary" PROCESSORS "1" WORKING_DIRECTORY "/home/chaste/src/")
add_test(TestOrganoidProliferativeTypes "/home/chaste/projects/Mammary/test/TestOrganoidProliferativeTypes")
set_tests_properties(TestOrganoidProliferativeTypes PROPERTIES  LABELS "Continuous_project_Mammary" PROCESSORS "1" WORKING_DIRECTORY "/home/chaste/src/")
add_test(TestOrganoidSpringForce "/home/chaste/projects/Mammary/test/TestOrganoidSpringForce")
set_tests_properties(TestOrganoidSpringForce PROPERTIES  LABELS "Continuous_project_Mammary" PROCESSORS "1" WORKING_DIRECTORY "/home/chaste/src/")
add_test(TestConnectivity "/home/chaste/projects/Mammary/test/TestConnectivity")
set_tests_properties(TestConnectivity PROPERTIES  LABELS "Continuous_project_Mammary" PROCESSORS "1" WORKING_DIRECTORY "/home/chaste/src/")
add_test(TestRadiiConnectSrn "/home/chaste/projects/Mammary/test/TestRadiiConnectSrn")
set_tests_properties(TestRadiiConnectSrn PROPERTIES  LABELS "Continuous_project_Mammary" PROCESSORS "1" WORKING_DIRECTORY "/home/chaste/src/")
add_test(TestPeriodicBilayer "/home/chaste/projects/Mammary/test/TestPeriodicBilayer")
set_tests_properties(TestPeriodicBilayer PROPERTIES  LABELS "Continuous_project_Mammary" PROCESSORS "1" WORKING_DIRECTORY "/home/chaste/src/")
add_test(TestSimCellesce "/home/chaste/projects/Mammary/test/TestSimCellesce")
set_tests_properties(TestSimCellesce PROPERTIES  LABELS "Continuous_project_Mammary" PROCESSORS "1" WORKING_DIRECTORY "/home/chaste/src/")
add_test(TestNDM "/home/chaste/projects/Mammary/test/TestNDM")
set_tests_properties(TestNDM PROPERTIES  LABELS "Continuous_project_Mammary" PROCESSORS "1" WORKING_DIRECTORY "/home/chaste/src/")
add_test(TestPressureLumenNDM "/home/chaste/projects/Mammary/test/TestPressureLumenNDM")
set_tests_properties(TestPressureLumenNDM PROPERTIES  LABELS "Continuous_project_Mammary" PROCESSORS "1" WORKING_DIRECTORY "/home/chaste/src/")
add_test(TestBuckleNDM "/home/chaste/projects/Mammary/test/TestBuckleNDM")
set_tests_properties(TestBuckleNDM PROPERTIES  LABELS "Continuous_project_Mammary" PROCESSORS "1" WORKING_DIRECTORY "/home/chaste/src/")
add_test(TestAdaptiveNDM3D "/home/chaste/projects/Mammary/test/TestAdaptiveNDM3D")
set_tests_properties(TestAdaptiveNDM3D PROPERTIES  LABELS "Continuous_project_Mammary" PROCESSORS "1" WORKING_DIRECTORY "/home/chaste/src/")
add_test(TestCurvatureStability "/home/chaste/projects/Mammary/test/TestCurvatureStability")
set_tests_properties(TestCurvatureStability PROPERTIES  LABELS "Continuous_project_Mammary" PROCESSORS "1" WORKING_DIRECTORY "/home/chaste/src/")
add_test(TestGrowingSpheroidSRN "/home/chaste/projects/Mammary/test/TestGrowingSpheroidSRN")
set_tests_properties(TestGrowingSpheroidSRN PROPERTIES  LABELS "Continuous_project_Mammary" PROCESSORS "1" WORKING_DIRECTORY "/home/chaste/src/")
add_test(TestODEsInCells "/home/chaste/projects/Mammary/test/TestODEsInCells")
set_tests_properties(TestODEsInCells PROPERTIES  LABELS "Continuous_project_Mammary" PROCESSORS "1" WORKING_DIRECTORY "/home/chaste/src/")
